name: chocolatine
run-name: pain-au-chocolat #
on :
  push: 
    branches-ignore:
      - 'ga-ignore-'
  pull_request:
    branches-ignore:
      - 'ga-ignore-'


env:
  MIRROR_URL: https://github.com/EpitechPromo2027/B-DOP-200-NCY-2-1-chocolatine-julian.bottiglione
  EXECUTABLE: "a.out,my_hunter"
jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container: 
      image: https://ghcr.io/epitech/coding-style-checker:latest
    steps:
      - run: check.sh . .
      
  check_program_compilation:
    runs-on: ubuntu-latest
    container: 
      image: https://ghcr.io/epitech/coding-style-checker:latest
    
    defaults:
      - run:
        shell: bash

    steps:
      - uses: "actions/checkout@v3"
      - run: make re
      
      - run: make clean

      - run: ls 
