name: chocolatine
run-name: pain-au-chocolat #
on :
  push: 
    branches-ignore:
      - 'ga-ignore-'
  pull_request:
    branches-ignore:
      - 'ga-ignore-'


env:
  MIRROR_URL: git@github.com:EpitechPromo2027/B-DOP-200-NCY-2-1-chocolatine-julian.bottiglione.git
  EXECUTABLE: "a.out" 

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: coding-style_checker
        run: |
          check.sh . .
          echo "::error file=coding-style-reports.log,line=1,col=5,endColumn=7::Minor error "


  check_program_compilation:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/epitech/coding-style-checker:latest
    
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: "actions/checkout@v3"
      - run: make
      
      - run: make clean 

      - run: |
        if [[test -f ${{ env.EXECUTABLE }} ]]; then
            echo "file exists"
        else
          exit 84
        fi

  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
             ${{ env.MIRROR_URL }}
          ssh_private_key:
             ${{ secrets.GIT_SSH_PRIVATE_KEY }}
